CREATE SCHEMA APT_DW.AUDIT;
create or replace sequence APT_DW.AUDIT.SEQ_ETL_TASK start = 1 increment = 1;
create or replace table APT_DW.AUDIT.ETL_TASK (
                TASK_KEY NUMBER(38,0)
                , PARENT_TASK_KEY VARCHAR
                , TASK_NAME VARCHAR
                , TASK_GROUP VARCHAR
                , EXECUTION_START_DATE TIMESTAMP_NTZ(9)
                , EXECUTION_STOP_DATE TIMESTAMP_NTZ(9)
                , CDC_TYPE NUMBER(38,0)
                , CDC_MIN_DATE TIMESTAMP_NTZ(9)
                , CDC_MAX_DATE TIMESTAMP_NTZ(9)
				, SYS_CHANGE_VERSION_START NUMBER(38,0)
				, SYS_CHANGE_VERSION_END NUMBER(38,0)
                , PRIMARY_SOURCE_DATABASE_NAME VARCHAR
                , PRIMARY_SOURCE_SCHEMA_NAME VARCHAR
                , PRIMARY_SOURCE_TABLE_NAME VARCHAR
                , TARGET_INITIAL_ROW_COUNT NUMBER(38,0)
                , EXTRACT_ROW_COUNT NUMBER(38,0)
                , TARGET_FINAL_ROW_COUNT NUMBER(38,0)
                , SOURCE_TYPE VARCHAR
                , DESTINATION_DATABASE_NAME VARCHAR
                , DESTINATION_SCHEMA_NAME VARCHAR
                , DESTINATION_TABLE_NAME VARCHAR
                , DESTINATION_OBJECT_VIEW_NAME VARCHAR
                , PIPELINE_RUN_ID VARCHAR
                , SUCCESSFUL_PROCESSING_IND BOOLEAN
);
SELECT * FROM APT_DW.AUDIT.ETL_TASK;




create or replace sequence APT_DW.AUDIT.SEQ_ETL_MESSAGE start = 1 increment = 1;
create or replace TABLE APT_DW.AUDIT.ETL_MESSAGE_LOG (
	MESSAGE_LOG_KEY NUMBER(38,0)
	, PIPELINE_RUN_ID VARCHAR
	, TASK_KEY NUMBER(38,0)
	, TASK_NAME VARCHAR(500)
	, MESSAGE_TYPE VARCHAR(25)
	, MESSAGE_DATE TIMESTAMP_NTZ(9)
	, MESSAGE_LOCATION VARCHAR(500)
	, MESSAGE VARCHAR(500)
);
SELECT * FROM APT_DW.AUDIT.ETL_MESSAGE_LOG;
